### ISSUE TITLE
Fehlerhafte Referenzierung eines Installation-Requirements

### ISSUE THREAD

**Issue by MaxClerkwell** [Hyogoro/artem_arbeitsvertrag_cmd#5]
https://github.com/Hyogoro/artem_arbeitsvertrag_cmd/blob/bb2eaf549928b39f262e3c55e8549cd6e1d601cd/requirements.txt#L1

Hier fehlen zwei fwd-slashes:
 git+ssh:**//**git@github.com

**Comment by Hyogoro** [comment]
Wurde angepasst
