### ISSUE TITLE
Weitere Ignores

### ISSUE THREAD

**Issue by MaxClerkwell** [Hyogoro/artem_arbeitsvertrag_cmd#6]
https://github.com/Hyogoro/artem_arbeitsvertrag_cmd/blob/bb2eaf549928b39f262e3c55e8549cd6e1d601cd/.gitignore#L132

In texdata/... befinden sich 
*.aux
*.fls
*.fdb_latxmk

Diese müssen beim Upload ignoriert werden.
Ggf ergibt es Sinn, eine komplette LaTeX-.gitignore mit an die jetzige .gitignore anzuhängen.

**Comment by Hyogoro** [comment]
Wurden hinzugefügt!
